services:
  # MariaDB Database Service
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./code:/var/www
    depends_on:
      - db

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./code:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # Node.js Service for Tailwind CSS
  node:
    image: node:alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./code:/var/www
    command: sh -c "npm install && npm run dev"
